//import './blocks/custom-cta';
//import './blocks/custom-cta2';
import './blocks/boat-infos-block';
import './blocks/custom-titre-style2';
import './blocks/galery-block';
//import './blocks/custom-cta4';
import './blocks/accordion';
import './blocks/accordion-block';
import './blocks/custom-button';